version: '3'

services:
  api:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - ./.docker/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: root
      POSTGRES_DB: billinho
    ports:
      - '5432:5432'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
