version: '3'

services:
  app:
    container_name: app_e2e_test
    build: .
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules # 'hack' prevents node_modules/ in the container from being overridden
    entrypoint: ./.docker/e2e/entrypoint.sh
    environment:
      NODE_ENV: test
      DB_TEST_HOSTNAME: db
      DB_TEST_PORT: ${DB_TEST_PORT}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_TEST_USERNAME: ${DB_TEST_USERNAME}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
    networks:
      - webnet
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:9.4
    networks:
      - webnet
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/e2e/.pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  pgdata:
  logs:
